// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.ui.web.jsf.controller.security;

import org.myorg.initial.roo.ui.web.jsf.controller.security.ApplicationBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplicationBean_Roo_Configurable {
    
    declare @type: ApplicationBean: @Configurable;
    
}
