// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.core.domain.security;

import org.myorg.initial.roo.core.domain.security.AuthRoleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AuthRoleDataOnDemand_Roo_Configurable {
    
    declare @type: AuthRoleDataOnDemand: @Configurable;
    
}
