// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.core.domain.security;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.myorg.initial.roo.core.domain.security.Principal;
import org.myorg.initial.roo.core.domain.security.PrincipalDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect PrincipalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PrincipalDataOnDemand: @Component;
    
    private Random PrincipalDataOnDemand.rnd = new SecureRandom();
    
    private List<Principal> PrincipalDataOnDemand.data;
    
    public Principal PrincipalDataOnDemand.getNewTransientPrincipal(int index) {
        Principal obj = new Principal();
        setActivationKey(obj, index);
        setEnabled(obj, index);
        setPassword(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void PrincipalDataOnDemand.setActivationKey(Principal obj, int index) {
        String activationKey = "activationKey_" + index;
        if (activationKey.length() > 100) {
            activationKey = activationKey.substring(0, 100);
        }
        obj.setActivationKey(activationKey);
    }
    
    public void PrincipalDataOnDemand.setEnabled(Principal obj, int index) {
        Boolean enabled = Boolean.TRUE;
        obj.setEnabled(enabled);
    }
    
    public void PrincipalDataOnDemand.setPassword(Principal obj, int index) {
        String password = "password_" + index;
        if (password.length() > 100) {
            password = password.substring(0, 100);
        }
        obj.setPassword(password);
    }
    
    public Principal PrincipalDataOnDemand.getSpecificPrincipal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Principal obj = data.get(index);
        Long id = obj.getId();
        return Principal.findPrincipal(id);
    }
    
    public Principal PrincipalDataOnDemand.getRandomPrincipal() {
        init();
        Principal obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Principal.findPrincipal(id);
    }
    
    public boolean PrincipalDataOnDemand.modifyPrincipal(Principal obj) {
        return false;
    }
    
    public void PrincipalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Principal.findPrincipalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Principal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Principal>();
        for (int i = 0; i < 10; i++) {
            Principal obj = getNewTransientPrincipal(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
