// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.core.domain.model;

import org.myorg.initial.roo.core.domain.model.HomeAddress;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HomeAddress_Roo_Configurable {
    
    declare @type: HomeAddress: @Configurable;
    
}
