// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.core.domain.model;

import javax.persistence.Entity;
import org.myorg.initial.roo.core.domain.model.HomeAddress;

privileged aspect HomeAddress_Roo_Jpa_Entity {
    
    declare @type: HomeAddress: @Entity;
    
}
