// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.core.domain.model;

import java.io.Serializable;
import org.myorg.initial.roo.core.domain.model.Person;

privileged aspect Person_Roo_Serializable {
    
    declare parents: Person implements Serializable;
    
    private static final long Person.serialVersionUID = 1L;
    
}
