// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.myorg.initial.roo.core.domain.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.myorg.initial.roo.core.domain.model.OtherAddress;
import org.myorg.initial.roo.core.domain.model.OtherAddressDataOnDemand;
import org.myorg.initial.roo.core.domain.reference.AddresLocationTypeEnum;
import org.myorg.initial.roo.core.domain.reference.AddressTypeEnum;
import org.myorg.initial.roo.core.domain.reference.CountryEnum;
import org.myorg.initial.roo.core.domain.reference.ProvinceEnum;
import org.springframework.stereotype.Component;

privileged aspect OtherAddressDataOnDemand_Roo_DataOnDemand {
    
    declare @type: OtherAddressDataOnDemand: @Component;
    
    private Random OtherAddressDataOnDemand.rnd = new SecureRandom();
    
    private List<OtherAddress> OtherAddressDataOnDemand.data;
    
    public OtherAddress OtherAddressDataOnDemand.getNewTransientOtherAddress(int index) {
        OtherAddress obj = new OtherAddress();
        setActive(obj, index);
        setAddresNumber(obj, index);
        setAddress(obj, index);
        setAddressType(obj, index);
        setCountry(obj, index);
        setLocationType(obj, index);
        setPopulation(obj, index);
        setPostalCode(obj, index);
        setProvince(obj, index);
        return obj;
    }
    
    public void OtherAddressDataOnDemand.setActive(OtherAddress obj, int index) {
        Boolean active = Boolean.TRUE;
        obj.setActive(active);
    }
    
    public void OtherAddressDataOnDemand.setAddresNumber(OtherAddress obj, int index) {
        String addresNumber = "addresNumber_" + index;
        if (addresNumber.length() > 250) {
            addresNumber = addresNumber.substring(0, 250);
        }
        obj.setAddresNumber(addresNumber);
    }
    
    public void OtherAddressDataOnDemand.setAddress(OtherAddress obj, int index) {
        String address = "address_" + index;
        if (address.length() > 250) {
            address = address.substring(0, 250);
        }
        obj.setAddress(address);
    }
    
    public void OtherAddressDataOnDemand.setAddressType(OtherAddress obj, int index) {
        AddressTypeEnum addressType = AddressTypeEnum.class.getEnumConstants()[0];
        obj.setAddressType(addressType);
    }
    
    public void OtherAddressDataOnDemand.setCountry(OtherAddress obj, int index) {
        CountryEnum country = CountryEnum.class.getEnumConstants()[0];
        obj.setCountry(country);
    }
    
    public void OtherAddressDataOnDemand.setLocationType(OtherAddress obj, int index) {
        AddresLocationTypeEnum locationType = AddresLocationTypeEnum.class.getEnumConstants()[0];
        obj.setLocationType(locationType);
    }
    
    public void OtherAddressDataOnDemand.setPopulation(OtherAddress obj, int index) {
        String population = "population_" + index;
        if (population.length() > 250) {
            population = population.substring(0, 250);
        }
        obj.setPopulation(population);
    }
    
    public void OtherAddressDataOnDemand.setPostalCode(OtherAddress obj, int index) {
        String postalCode = "postalCo_" + index;
        if (postalCode.length() > 10) {
            postalCode = postalCode.substring(0, 10);
        }
        obj.setPostalCode(postalCode);
    }
    
    public void OtherAddressDataOnDemand.setProvince(OtherAddress obj, int index) {
        ProvinceEnum province = ProvinceEnum.class.getEnumConstants()[0];
        obj.setProvince(province);
    }
    
    public OtherAddress OtherAddressDataOnDemand.getSpecificOtherAddress(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        OtherAddress obj = data.get(index);
        Long id = obj.getId();
        return OtherAddress.findOtherAddress(id);
    }
    
    public OtherAddress OtherAddressDataOnDemand.getRandomOtherAddress() {
        init();
        OtherAddress obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return OtherAddress.findOtherAddress(id);
    }
    
    public boolean OtherAddressDataOnDemand.modifyOtherAddress(OtherAddress obj) {
        return false;
    }
    
    public void OtherAddressDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = OtherAddress.findOtherAddressEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'OtherAddress' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<OtherAddress>();
        for (int i = 0; i < 10; i++) {
            OtherAddress obj = getNewTransientOtherAddress(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
